// XCLABEL Website — Multi-language support
// Languages: en (English), ru (Russian), ro (Romanian)

const TRANSLATIONS = {
  en: {
    // Nav — shared
    'nav.home':       'Home',
    'nav.solutions':  'Solutions',
    'nav.contact':    'Contact',
    'nav.oht':        'Owl Hoot Tech',

    // Index hero
    'idx.tagline':    'Revolutionary AR-Powered Solutions',
    'idx.desc':       'Patent-protected technology transforming digital networking and spatial experiences. Choose your solution below.',
    'idx.choose':     'Choose Your Solution',

    // Index XCLABEL card
    'xc.subtitle':    'Digital Networking & AR Billboards',
    'xc.desc':        'Instant face recognition + BLE = automatic digital business cards + smart AR billboards that can\'t be blocked. For enterprises, creators, dating events, and retail.',
    'xc.btn':         'Explore XCLABEL',
    'xc.stat1.label': 'Market Opportunity',
    'xc.stat2.label': 'Connection Time',
    'xc.stat3.label': 'BLE Range',

    // Index Airport card
    'ap.subtitle':    'Complete AR Solution for Airports & Transit Hubs',
    'ap.desc':        'Real-time AR navigation + contactless security verification for airports. Transform passenger experience with seamless wayfinding and 0.3-second biometric checkpoints. Reduce security wait times by 40% while enhancing safety.',
    'ap.btn':         'Explore XCLABEL Airport',
    'ap.stat1.label': 'Faster Security',
    'ap.stat2.label': 'Verification',
    'ap.stat3.label': 'AR Navigation',

    // Index OHT card
    'oht.subtitle':   'Enterprise Software Studio — 10 Products',
    'oht.desc':       'The company behind XCLABEL. Owl Hoot Tech builds specialised enterprise software across ERP, BI, RPA, logistics, accessibility, and AR — targeting EUR 400B+ in combined addressable markets.',
    'oht.btn':        'Learn About OHT',
    'oht.stat1.val':  '10+',
    'oht.stat1.label':'Products',
    'oht.stat2.val':  'EUR 2–15M',
    'oht.stat2.label':'Seeking',
    'oht.stat3.val':  'EUR 8.4M',
    'oht.stat3.label':'ARR Year 3',

    // Unified benefits
    'ben.title':      'Unified Technology Platform',
    'ben.sub':        'Both solutions powered by the same patent-protected AR infrastructure',
    'ben.1.title':    'Patent Protected',
    'ben.1.desc':     'Core technology owned by Marif Bergan with international protection',
    'ben.2.title':    'Global Scale',
    'ben.2.desc':     'ARCore & Spark AR compatible, ready for worldwide deployment',
    'ben.3.title':    'Real-time Sync',
    'ben.3.desc':     'BLE + AR fusion with offline-first architecture',
    'ben.4.title':    'Blue Ocean',
    'ben.4.desc':     'No direct competitors in AR + BLE networking space',

    // CTA shared
    'cta.idx.h2':     'Ready to transform your industry?',
    'cta.idx.p':      'Whether you\'re looking for digital networking or airport navigation, XCLABEL has the patent-backed solution.',
    'cta.note':       'or call +373 68 761 110',

    // Footer
    'footer.copy':    '© {year} XCLABEL. Patent owned by Marif Bergan. Face recognition + BLE + Smart AR Technology.',
    'footer.contact': 'Contact',

    // ── OHT Product cards ─────────────────────────────────────────
    'oht.prod.xc.tag':      'AR · Networking',
    'oht.prod.xc.desc':     'Patent-protected face recognition + BLE = automatic digital business cards in 0.3 s. Smart AR billboards anchored to real-world surfaces that can\'t be blocked by ad blockers. For enterprises, live events, retail, and dating apps.',
    'oht.prod.ap.tag':      'AR · Aviation',
    'oht.prod.ap.desc':     'Real-time AR navigation and contactless passenger verification for airports. BLE beacon tracking, face recognition security checkpoints (0.3 s per passenger), flight ticket integration, and multi-floor wayfinding. 40% faster boarding.',
    'oht.prod.perch.tag':   'ERP · SME',
    'oht.prod.perch.desc':  'Lightweight on-premise ERP for SMEs — simpler than 1C, cheaper than SAP. Modules: Finance (double-entry, TVA), Inventory (FIFO), CRM, Sales, Procurement, HR with Moldova payroll (CAS/CASS). Built-in 1C XML importer, FastAPI REST, Docker-ready Studio UI.',
    'oht.prod.strix.tag':   'BI · Analytics',
    'oht.prod.strix.desc':  'Self-service BI platform that connects to SQL databases, Excel files, Perch ERP, and Glide RPA. Drag-and-drop dashboards, scheduled PDF reports, metric-based alert rules. On-premise, no cloud lock-in, no AI black boxes.',
    'oht.prod.glide.tag':   'RPA · Automation',
    'oht.prod.glide.desc':  'Python-native RPA platform — faster to set up than UiPath, zero licensing fees. Define workflows in YAML, automate browsers with Playwright, orchestrate REST APIs, run jobs concurrently via asyncio. MIT open core, Docker-ready, live Studio web dashboard.',
    'oht.prod.hollow.tag':  'WMS · Logistics',
    'oht.prod.hollow.desc': 'Virtual warehouse management system. Configurable 3D grid layout (rows × columns × levels), color-coded zone management, stock entries per shelf position, and a full FastAPI REST backend with a real-time Studio dashboard for inventory control.',
    'oht.prod.telepat.tag': 'Accessibility · Gaze',
    'oht.prod.telepat.desc':'Hands-free phone control via real-time eye-tracking. The front camera and TensorFlow Lite model continuously track gaze position — dwell on any element to tap it. Smile-to-click, calibration activity, PRECISION preset, and smooth animated gaze overlay. Designed for motor-impaired users and hands-free workflows.',
    'oht.prod.xproj.tag':   'AR · Wireless Display',
    'oht.prod.xproj.desc':  'AR surface projector + wireless screen mirror in one app. AR mode uses ARCore/Sceneform to anchor content onto real-world surfaces. Wireless mode captures the screen and streams it at up to 60 fps H.264 (12 Mbps) to nearby devices via Google Nearby Connections — no cables, no router needed.',
    'oht.prod.xcdock.tag':  'Bluetooth · Hub',
    'oht.prod.xcdock.desc': 'Turns any Android phone into a virtual Bluetooth dock station. Simultaneously scans and manages headphones, speakers, TVs, computers, and tablets over BT Classic, BLE, and Wi-Fi Direct. Real-time RSSI signal bars, device type detection, and a VirtualHub engine that routes source-to-receiver connections.',
    'oht.prod.icswigl.tag': 'Accessibility · Display',
    'oht.prod.icswigl.desc':'System-wide font and display scaling for Android, controlled by voice. Say "Hey Wigl set 3" to change text size instantly, or "Wigl Wigl" to trigger an emergency flashlight. Includes TV mode for external screens, standalone web reader with custom zoom, and flash notifications. Supports Russian, Romanian, and English.',

    // xclabel.html
    'xch1':           'XCLABEL — Revolutionary AR-Powered Digital Networking',
    'xch1.p':         'First-in-world technology: automatic face recognition + BLE = instant digital business cards + smart AR billboards that can\'t be blocked. Transforming the $50B+ digital networking market with verifiable, immersive, offline-first experiences.',
    'xch1.btn1':      'Schedule Enterprise Demo',
    'xch1.btn2':      'Explore the Platform',
    'xch1.m1':        'Patent owned by Marif Bergan',
    'xch1.m2':        'Face recognition + BLE + AR Smart Billboards',
    'xch1.m3':        'Blue Ocean · No direct competitors',
    'xc.card.h3':     'Immersive Smart Billboard',
    'xc.card.p':      'Transparent AR overlay with verified identity, real-time analytics, and dynamic creative.',
    'xc.demo.eyebrow':'Live product preview',
    'xc.demo.h2':     'Instant face-to-face overlays that close the loop in seconds.',
    'xc.demo.p':      'XCLABEL locks onto the face, pulls verified reach, and delivers actionable buttons that work even when the venue is offline.',
    'xc.demo.li1':    '<strong>Trust-first identity:</strong> relationship status plus certified audience metrics at a glance.',
    'xc.demo.li2':    '<strong>Monetizable engagement:</strong> "Open" drives any destination, "Copy" pushes the link to any channel.',
    'xc.demo.li3':    '<strong>Offline-to-online bridge:</strong> patented BLE sync replaces QR scans and NFC taps.',
    'xc.demo.btn1':   'Book live walkthrough',
    'xc.demo.btn2':   'See the stack',
    'xc.prob.h2':     'The problem: inefficient networking costs money',
    'xc.prob.h3a':    'Current reality',
    'xc.prob.li1a':   '15+ seconds to exchange contact information',
    'xc.prob.li2a':   '40% of physical cards get lost or damaged',
    'xc.prob.li3a':   'Zero real-time updates or synchronization',
    'xc.prob.li4a':   'No way to block competitors from offline advertising',
    'xc.prob.li5a':   'Creators & dating events lose warm leads after activations',
    'xc.prob.h3b':    'Market impact',
    'xc.prob.li1b':   '$50B+ market opportunity · 25% CAGR growth',
    'xc.prob.li2b':   '250M+ users worldwide affected by lost data',
    'xc.prob.li3b':   'Lost first-party data = wasted spend & productivity',
    'xc.prob.li4b':   'Google/Meta creators lack verified offline conversions',
    'xc.tech.h2':     'Two revolutionary technologies in one',
    'xc.tech.p':      'Patent-protected XCLABEL workflow that fuses computer vision, BLE, and AR spatial media.',
    'xc.tech.s1.h3':  'Instant Digital IDs',
    'xc.tech.s1.p':   '0.3-second automatic face recognition + BLE handshake delivers instant digital business cards without scanning.',
    'xc.tech.s2.h3':  'Live Data Sync',
    'xc.tech.s2.p':   '10-meter wireless range updates Google Contacts, YouTube Creator Studio, and Meta Business Suite in real time.',
    'xc.tech.s3.h3':  'Smart AR Billboards',
    'xc.tech.s3.p':   'Transparent video overlays with analytics that can\'t be blocked, ARCore/Spark AR compatible, ready for Quest mixed reality.',
    'xc.uses.h3':     'Cross-vertical use cases',
    'xc.uses.li1':    '<strong>Enterprise</strong> — HQ lobbies, trade shows, executive summits',
    'xc.uses.li2':    '<strong>Creators & influencers</strong> — meetups, tours, fan activations',
    'xc.uses.li3':    '<strong>Retail & campuses</strong> — geo-fenced merchandising & campus services',
    'xc.uses.li4':    '<strong>Dating & social</strong> — trust-first identity exchange with offline proof',
    'xc.market.h2':   '$50B+ market opportunity',
    'xc.market.a1h3': 'Total addressable',
    'xc.market.a1p':  'Digital identity ($2.3T globally), AR/VR advertising ($455B), networking solutions ($15B).',
    'xc.market.a2h3': 'Serviceable market',
    'xc.market.a2p':  '$8B SAM across B2C and B2B (500K corporations + 50K agencies).',
    'xc.market.a3h3': 'Growth velocity',
    'xc.market.a3p':  '25% CAGR with zero direct competitors — a true blue ocean opportunity.',
    'xc.market.a4h3': 'Visibility advantage',
    'xc.market.a4p':  'Smart billboards remain 100% viewable, bypass ad blockers, and deliver first-party analytics.',
    'xc.moat.h2':     'First-mover advantage: patent-protected technology',
    'xc.rev.h2':      'Multiple revenue streams (high margins)',
    'xc.rev.a1h3':    'Creator & influencer subscriptions',
    'xc.rev.a1p':     '$4.99/month premium · Target 5M creators · $600M annual revenue · 80-90% gross margin.',
    'xc.rev.a2h3':    'AR advertising inventory',
    'xc.rev.a2p':     '$2.50 per impression with 100% visibility · 100M impressions by Year 3 · $250M revenue.',
    'xc.rev.a3h3':    'Enterprise licensing',
    'xc.rev.a3p':     '$99–$999/month per organization · 10K corporate clients by Year 3 · $240M revenue.',
    'xc.rev.a4h3':    'API & platform licensing',
    'xc.rev.a4p':     '$0.10 per API call via Google Maps / Android OEM · 1B calls by Year 3 · $100M revenue.',
    'xc.fin.h2':      'Financial trajectory',
    'xc.fin.y1h3':    '$2.5M revenue',
    'xc.fin.y1p':     'Initial enterprise pilots + creator subscriptions.',
    'xc.fin.y2h3':    '$31.5M revenue',
    'xc.fin.y2p':     '12.6× growth with advertising roll-out and Advantage+ partnerships.',
    'xc.fin.y3h3':    '$195M revenue',
    'xc.fin.y3p':     '6.2× growth — creators, dating, and retail activations at scale.',
    'xc.fin.y5h3':    '$1.44B revenue',
    'xc.fin.y5p':     'Global deployment with 80–90% margins, CAC $15, LTV $180 (12:1 LTV/CAC).',
    'xc.val.h3':      'Investment & Acquisition',
    'xc.val.li1':     'Seeking: EUR 2–15M — strategic acquisition or early-stage investment',
    'xc.val.li2':     'ROI for acquirer: 156% IRR on long-term platform trajectory',
    'xc.val.li3':     'Consumer adoption: 60% usage at creator & dating events by Year 3',
    'xc.val.li4':     'Gross margin: 80–90% with recurring revenues',
    'xc.part.h2':     'Strategic fit with Google & Meta',
    'xc.part.a3h3':   'Transaction options',
    'xc.part.a3p':    'Strategic acquisition (EUR 2–15M), seed investment round (EUR 2–8M), or exclusive IP licensing with upfront payment. Working demo available on request.',
    'xc.ip.pat.step': 'Patent',
    'xc.ip.pat.h3':   'AGEPI Nr. 7598 — Final examination stage',
    'xc.ip.pat.p':    'Filed 18 November 2025. Currently at substantive examination (cerere de examinare de fond) — the final stage before grant. Core workflow: face recognition + BLE instant exchange + smart AR billboard orchestration.',
    'xc.ip.copy.step':'Copyright',
    'xc.ip.copy.h3':  'Seria PC Nr. 8320 — Software registered',
    'xc.ip.copy.p':   'Copyright certificate issued 21 October 2025 by AGEPI for the XCLABEL software. Full source code and IP owned by Marif Bergan.',
    'xc.ip.h2':       'Intellectual property protection',
    'xc.cta.h2':      'Ready to co-create the next era of spatial networking?',
    'xc.cta.p':       'XCLABEL is the patent-backed blue ocean platform for immersive identity. Let\'s build pilots for Google, Meta, and flagship venues.',
    'xc.nav.problem': 'Problem',
    'xc.nav.demo':    'Demo',
    'xc.nav.tech':    'Technology',
    'xc.nav.market':  'Market',
    'xc.nav.revenue': 'Revenue',
    'xc.nav.partners':'Partners',
    'xc.nav.pitch':   'Request Pitch',

    // airport.html
    'ap.h1':          'XCLABEL Airport — Complete AR Solution for Airports',
    'ap.h1.p':        'Transform the passenger experience with real-time AR navigation, contactless security verification, and seamless wayfinding. From check-in to boarding, powered by patent-protected face recognition + BLE technology.',
    'ap.btn1':        'Schedule Airport Demo',
    'ap.btn2':        'See the Technology',
    'ap.m1':          'Patent owned by Marif Bergan',
    'ap.m2':          'AR Navigation + Face Recognition + BLE',
    'ap.m3':          '40% Faster Checkpoints',
    'ap.nav.challenge':'Challenge',
    'ap.nav.nav':     'Navigation',
    'ap.nav.security':'Security',
    'ap.nav.tech':    'Technology',
    'ap.nav.benefits':'Benefits',
    'ap.nav.market':  'Market',
    'ap.nav.demo':    'Request Demo',

    // owlhoot.html
    'oht.h1':         'Owl Hoot Tech',
    'oht.h1.sub':     'Building Tomorrow\'s Enterprise Software — Today.',
    'oht.h1.p':       'A European deep-tech studio founded in 2026 with 10 specialised enterprise software products across AR, logistics, ERP, BI, RPA, and accessibility. Targeting EUR 400B+ in combined addressable markets.',
    'oht.h1.btn1':    'Investor Information',
    'oht.h1.btn2':    'Become a Partner',
    'oht.mission.h2': 'Our Mission',
    'oht.mission.p':  'To deliver purposefully engineered software solutions — each product solves a specific high-value problem for enterprise customers, with the quality, security, and scalability that modern organisations demand.',
    'oht.vision.h2':  'Our Vision',
    'oht.vision.p':   'To become the leading European deep-tech studio building hyper-specialised enterprise software that transforms how businesses operate, communicate, and compete globally.',
    'oht.products.h2':'Our 10 Products',
    'oht.products.sub':'Each product is the best tool for its specific job — deeply specialised, cloud-native, and built to enterprise standards.',
    'oht.inv.h2':     'For Investors',
    'oht.inv.sub':    'A rare opportunity: 10 enterprise software products, EUR 400B+ combined TAM, seeking EUR 2–15M seed funding.',
    'oht.inv.ask.h3': 'Investment Ask',
    'oht.inv.round':  'Round Type',
    'oht.inv.round.v':'Seed / Pre-Series A',
    'oht.inv.amount': 'Amount Sought',
    'oht.inv.amount.v':'EUR 2M (minimum) — EUR 15M (full round)',
    'oht.inv.val':    'Valuation (indicative)',
    'oht.inv.val.v':  'EUR 8–15M pre-money',
    'oht.inv.use':    'Use of Proceeds',
    'oht.inv.use.v':  'Engineering (45%), Sales & Marketing (25%), Operations (15%), Infrastructure (10%), Reserve (5%)',
    'oht.inv.run':    'Runway',
    'oht.inv.run.v':  '18–24 months to Series A / cashflow breakeven on top products',
    'oht.inv.metrics.h3':'Key Metrics',
    'oht.inv.m1':     'Products in portfolio',
    'oht.inv.m1.v':   '10 enterprise software products',
    'oht.inv.m2':     'Combined TAM',
    'oht.inv.m2.v':   'USD 304B+ globally',
    'oht.inv.m3':     'Y3 ARR projection',
    'oht.inv.m3.v':   'EUR 8.4M (combined portfolio)',
    'oht.inv.m4':     'Gross margin target',
    'oht.inv.m4.v':   '70–80% at scale (SaaS products)',
    'oht.inv.m5':     'Business model',
    'oht.inv.m5.v':   'SaaS + enterprise licence + professional services',
    'oht.inv.m6':     'Target markets',
    'oht.inv.m6.v':   'Europe, MENA, North America',
    'oht.inv.cta':    'Request Investor Deck',
    'oht.partner.h2': 'Become a Partner',
    'oht.partner.sub':'We are actively seeking resellers, system integrators, and technology partners to expand our reach across Europe and MENA.',
    'oht.partner.1.h3':'Reseller Partners',
    'oht.partner.1.p':'Sell and implement OHT products under your brand. Competitive margins, full technical support, and co-marketing resources.',
    'oht.partner.2.h3':'Technology Integration',
    'oht.partner.2.p':'Connect your platform to OHT\'s products via our open APIs. Expand your offering with best-in-class specialised tools.',
    'oht.partner.3.h3':'Strategic Investment',
    'oht.partner.3.p':'Co-invest and take an equity position. Access to full financial data, board observer rights, and co-development agreements.',
    'oht.partner.btn': 'Contact Us to Partner',
    'oht.cta.h2':     'Ready to build something extraordinary?',
    'oht.cta.p':      'Whether you are an investor, partner, or enterprise customer — we would love to hear from you.',
    'oht.footer':     '© {year} Owl Hoot Tech. Founded 2026. All rights reserved.',
  },

  ru: {
    'nav.home':       'Главная',
    'nav.solutions':  'Решения',
    'nav.contact':    'Контакт',
    'nav.oht':        'Owl Hoot Tech',

    'idx.tagline':    'Революционные AR-решения',
    'idx.desc':       'Запатентованная технология, трансформирующая цифровые коммуникации и пространственный опыт. Выберите решение ниже.',
    'idx.choose':     'Выберите решение',

    'xc.subtitle':    'Цифровые коммуникации и AR-билборды',
    'xc.desc':        'Мгновенное распознавание лиц + BLE = автоматические цифровые визитки + умные AR-билборды, которые невозможно заблокировать. Для предприятий, создателей контента, организаторов мероприятий и ритейла.',
    'xc.btn':         'Подробнее о XCLABEL',
    'xc.stat1.label': 'Объём рынка',
    'xc.stat2.label': 'Время подключения',
    'xc.stat3.label': 'Дальность BLE',

    'ap.subtitle':    'Полное AR-решение для аэропортов',
    'ap.desc':        'AR-навигация в реальном времени + бесконтактная верификация для аэропортов. Сократите время досмотра на 40%, улучшив безопасность и комфорт пассажиров.',
    'ap.btn':         'Подробнее об XCLABEL Airport',
    'ap.stat1.label': 'Быстрее досмотр',
    'ap.stat2.label': 'Верификация',
    'ap.stat3.label': 'AR-навигация',

    'oht.subtitle':   'Студия корпоративного ПО — 10 продуктов',
    'oht.desc':       'Компания, создавшая XCLABEL. Owl Hoot Tech разрабатывает специализированное корпоративное ПО в области ERP, BI, RPA, логистики, доступности и AR.',
    'oht.btn':        'Узнать об OHT',
    'oht.stat1.val':  '10+',
    'oht.stat1.label':'Продуктов',
    'oht.stat2.val':  'EUR 2–15М',
    'oht.stat2.label':'Привлекаем',
    'oht.stat3.val':  'EUR 8.4М',
    'oht.stat3.label':'ARR 3-й год',

    'ben.title':      'Единая технологическая платформа',
    'ben.sub':        'Оба решения работают на одной запатентованной AR-инфраструктуре',
    'ben.1.title':    'Патентная защита',
    'ben.1.desc':     'Ключевая технология принадлежит Марифу Бергану с международной защитой',
    'ben.2.title':    'Глобальный масштаб',
    'ben.2.desc':     'Совместимость с ARCore и Spark AR, готово к мировому развёртыванию',
    'ben.3.title':    'Синхронизация в реальном времени',
    'ben.3.desc':     'Слияние BLE и AR с офлайн-архитектурой',
    'ben.4.title':    'Голубой океан',
    'ben.4.desc':     'Нет прямых конкурентов в нише AR + BLE коммуникаций',

    'cta.idx.h2':     'Готовы трансформировать свою отрасль?',
    'cta.idx.p':      'Будь то цифровые коммуникации или навигация в аэропорту — у XCLABEL есть запатентованное решение.',
    'cta.note':       'или позвоните +373 68 761 110',

    'footer.copy':    '© {year} XCLABEL. Патент принадлежит Марифу Бергану. Распознавание лиц + BLE + Smart AR.',
    'footer.contact': 'Контакт',

    // ── OHT Product cards ─────────────────────────────────────────
    'oht.prod.xc.tag':      'AR · Коммуникации',
    'oht.prod.xc.desc':     'Запатентованное распознавание лиц + BLE = автоматические цифровые визитки за 0,3 с. Умные AR-билборды, закреплённые на реальных поверхностях, которые невозможно заблокировать блокировщиками рекламы. Для предприятий, мероприятий, ритейла и приложений знакомств.',
    'oht.prod.ap.tag':      'AR · Авиация',
    'oht.prod.ap.desc':     'AR-навигация в реальном времени и бесконтактная верификация пассажиров для аэропортов. BLE-маяки, распознавание лиц на КПП (0,3 с на пассажира), интеграция с билетами и многоэтажная навигация. Посадка на 40% быстрее.',
    'oht.prod.perch.tag':   'ERP · МСБ',
    'oht.prod.perch.desc':  'Лёгкая локальная ERP для малого и среднего бизнеса — проще, чем 1С, дешевле, чем SAP. Модули: Финансы (двойная запись, НДС), Склад (ФИФО), CRM, Продажи, Закупки, HR с расчётом зарплаты Молдовы (CAS/CASS). Импорт XML 1С, FastAPI REST, Docker-ready Studio.',
    'oht.prod.strix.tag':   'BI · Аналитика',
    'oht.prod.strix.desc':  'Self-service BI-платформа, подключающаяся к SQL-базам, Excel, Perch ERP и Glide RPA. Конструктор дашбордов drag-and-drop, запланированные PDF-отчёты, правила оповещений по метрикам. Локальное развёртывание, без облачной зависимости.',
    'oht.prod.glide.tag':   'RPA · Автоматизация',
    'oht.prod.glide.desc':  'Python-нативная RPA-платформа — быстрее UiPath, нулевые лицензионные сборы. Определяйте рабочие процессы в YAML, автоматизируйте браузеры через Playwright, оркеструйте REST API, запускайте задания параллельно через asyncio. MIT open core, Docker-ready.',
    'oht.prod.hollow.tag':  'WMS · Логистика',
    'oht.prod.hollow.desc': 'Виртуальная система управления складом. Настраиваемая 3D-сетка (ряды × столбцы × уровни), управление зонами с цветовой кодировкой, записи запасов на позицию и FastAPI REST бэкенд с дашбордом Studio в реальном времени.',
    'oht.prod.telepat.tag': 'Доступность · Взгляд',
    'oht.prod.telepat.desc':'Управление телефоном руками-free через отслеживание взгляда в реальном времени. Фронтальная камера и модель TensorFlow Lite отслеживают позицию взгляда — задержитесь на элементе чтобы нажать. Клик по улыбке, калибровка, пресет PRECISION.',
    'oht.prod.xproj.tag':   'AR · Беспроводной дисплей',
    'oht.prod.xproj.desc':  'AR-проектор поверхностей + беспроводное зеркало экрана в одном приложении. AR-режим использует ARCore/Sceneform. Беспроводной режим транслирует экран до 60 fps H.264 (12 Mbps) через Google Nearby Connections — без кабелей и роутера.',
    'oht.prod.xcdock.tag':  'Bluetooth · Хаб',
    'oht.prod.xcdock.desc': 'Превращает любой Android в виртуальный Bluetooth-хаб. Одновременно сканирует наушники, колонки, телевизоры, компьютеры через BT Classic, BLE и Wi-Fi Direct. Бары RSSI в реальном времени, определение типа устройства, движок VirtualHub.',
    'oht.prod.icswigl.tag': 'Доступность · Дисплей',
    'oht.prod.icswigl.desc':'Системное масштабирование шрифта и дисплея Android, управляемое голосом. Скажите "Hey Wigl set 3" для мгновенного изменения размера текста, или "Wigl Wigl" для экстренного фонарика. TV-режим, автономный веб-ридер, флэш-уведомления.',

    'xch1':           'XCLABEL — Революционные AR-коммуникации',
    'xch1.p':         'Технология мирового первенства: автоматическое распознавание лиц + BLE = мгновенные цифровые визитки + умные AR-билборды, которые невозможно заблокировать.',
    'xch1.btn1':      'Запросить демо',
    'xch1.btn2':      'Изучить платформу',
    'xch1.m1':        'Патент принадлежит Марифу Бергану',
    'xch1.m2':        'Распознавание лиц + BLE + AR-билборды',
    'xch1.m3':        'Голубой океан · Нет прямых конкурентов',
    'xc.card.h3':     'Умный AR-билборд',
    'xc.card.p':      'Прозрачный AR-оверлей с верифицированной идентичностью, аналитикой в реальном времени и динамическим контентом.',
    'xc.demo.eyebrow':'Демонстрация продукта',
    'xc.demo.h2':     'Мгновенные оверлеи лицо-к-лицу, замыкающие цикл за секунды.',
    'xc.demo.p':      'XCLABEL определяет лицо, извлекает верифицированный охват и предоставляет кнопки действий, работающие даже офлайн.',
    'xc.demo.li1':    '<strong>Идентичность в приоритете:</strong> статус отношений и сертифицированные метрики аудитории с первого взгляда.',
    'xc.demo.li2':    '<strong>Монетизируемое взаимодействие:</strong> «Открыть» ведёт на любой ресурс, «Копировать» отправляет ссылку в любой канал.',
    'xc.demo.li3':    '<strong>Офлайн-онлайн мост:</strong> запатентованная BLE-синхронизация заменяет QR-коды и NFC.',
    'xc.demo.btn1':   'Живая демонстрация',
    'xc.demo.btn2':   'Технический стек',
    'xc.prob.h2':     'Проблема: неэффективные коммуникации стоят денег',
    'xc.prob.h3a':    'Текущая реальность',
    'xc.prob.li1a':   'Более 15 секунд на обмен контактной информацией',
    'xc.prob.li2a':   '40% физических визиток теряется или повреждается',
    'xc.prob.li3a':   'Нет обновлений в реальном времени',
    'xc.prob.li4a':   'Невозможно заблокировать конкурентов от офлайн-рекламы',
    'xc.prob.li5a':   'Создатели и мероприятия теряют тёплые лиды',
    'xc.prob.h3b':    'Влияние на рынок',
    'xc.prob.li1b':   'Рынок $50B+ · рост 25% CAGR',
    'xc.prob.li2b':   'Более 250 млн пользователей в мире затронуты потерей данных',
    'xc.prob.li3b':   'Потеря first-party данных = пустые расходы',
    'xc.prob.li4b':   'Создателям Google/Meta не хватает верифицированных офлайн-конверсий',
    'xc.tech.h2':     'Две революционные технологии в одном',
    'xc.tech.p':      'Запатентованный рабочий процесс XCLABEL, объединяющий компьютерное зрение, BLE и AR.',
    'xc.tech.s1.h3':  'Мгновенные цифровые ID',
    'xc.tech.s1.p':   'Автоматическое распознавание лиц за 0,3 секунды + BLE-хэндшейк без сканирования.',
    'xc.tech.s2.h3':  'Синхронизация данных в реальном времени',
    'xc.tech.s2.p':   'Дальность 10 метров обновляет Google Контакты и Meta Business Suite в реальном времени.',
    'xc.tech.s3.h3':  'Умные AR-билборды',
    'xc.tech.s3.p':   'Прозрачные видеооверлеи с аналитикой, совместимые с ARCore/Spark AR.',
    'xc.uses.h3':     'Применение в разных отраслях',
    'xc.uses.li1':    '<strong>Предприятия</strong> — офисы, выставки, деловые саммиты',
    'xc.uses.li2':    '<strong>Создатели и инфлюенсеры</strong> — встречи, туры, фан-активации',
    'xc.uses.li3':    '<strong>Ритейл и кампусы</strong> — геозонированный мерчандайзинг',
    'xc.uses.li4':    '<strong>Знакомства и социальные сети</strong> — доверенный обмен идентичностью',
    'xc.market.h2':   'Рыночная возможность $50B+',
    'xc.market.a1h3': 'Общий адресуемый рынок',
    'xc.market.a1p':  'Цифровая идентичность ($2.3T), AR/VR реклама ($455B), сетевые решения ($15B).',
    'xc.market.a2h3': 'Обслуживаемый рынок',
    'xc.market.a2p':  '$8B SAM: B2C и B2B (500K корпораций + 50K агентств).',
    'xc.market.a3h3': 'Скорость роста',
    'xc.market.a3p':  '25% CAGR без прямых конкурентов — настоящий голубой океан.',
    'xc.market.a4h3': 'Преимущество видимости',
    'xc.market.a4p':  'Умные билборды всегда видимы, обходят блокировщики рекламы.',
    'xc.moat.h2':     'Преимущество первопроходца: запатентованная технология',
    'xc.rev.h2':      'Множество источников дохода (высокая маржинальность)',
    'xc.rev.a1h3':    'Подписки создателей',
    'xc.rev.a1p':     '$4.99/мес · 5М создателей · $600М выручки · маржа 80-90%.',
    'xc.rev.a2h3':    'AR-рекламный инвентарь',
    'xc.rev.a2p':     '$2.50 за показ · 100М показов к 3-му году · $250М выручки.',
    'xc.rev.a3h3':    'Корпоративное лицензирование',
    'xc.rev.a3p':     '$99–$999/мес · 10К корпоративных клиентов · $240М выручки.',
    'xc.rev.a4h3':    'Лицензирование API и платформы',
    'xc.rev.a4p':     '$0.10 за вызов API · 1B вызовов к 3-му году · $100М выручки.',
    'xc.fin.h2':      'Финансовая траектория',
    'xc.fin.y1h3':    '$2.5М выручки',
    'xc.fin.y1p':     'Первоначальные корпоративные пилоты + подписки создателей.',
    'xc.fin.y2h3':    '$31.5М выручки',
    'xc.fin.y2p':     'Рост в 12.6× с запуском рекламы и партнёрствами Advantage+.',
    'xc.fin.y3h3':    '$195М выручки',
    'xc.fin.y3p':     'Рост в 6.2× — создатели, знакомства и ритейл.',
    'xc.fin.y5h3':    '$1.44B выручки',
    'xc.fin.y5p':     'Глобальное развёртывание с маржой 80–90%, CAC $15, LTV $180.',
    'xc.val.h3':      'Инвестиции и приобретение',
    'xc.val.li1':     'Запрашиваем: EUR 2–15M — стратегическое поглощение или инвестиция на ранней стадии',
    'xc.val.li2':     'ROI для приобретателя: 156% IRR на долгосрочной траектории платформы',
    'xc.val.li3':     'Потребительское принятие: 60% использования к 3-му году',
    'xc.val.li4':     'Валовая маржа: 80–90% при рекуррентных доходах',
    'xc.part.h2':     'Стратегическое соответствие Google и Meta',
    'xc.part.a3h3':   'Варианты сделки',
    'xc.part.a3p':    'Стратегическое поглощение (EUR 2–15M), инвестиционный раунд seed (EUR 2–8M) или эксклюзивное IP-лицензирование с авансовым платежом. Рабочее демо доступно по запросу.',
    'xc.ip.pat.step': 'Патент',
    'xc.ip.pat.h3':   'AGEPI №7598 — Финальная стадия экспертизы',
    'xc.ip.pat.p':    'Подан 18 ноября 2025 г. Статус: экспертиза по существу (cerere de examinare de fond) — финальный этап перед выдачей. Ключевой процесс: распознавание лиц + мгновенный BLE-обмен + умные AR-билборды.',
    'xc.ip.copy.step':'Авторское право',
    'xc.ip.copy.h3':  'Seria PC №8320 — ПО зарегистрировано',
    'xc.ip.copy.p':   'Свидетельство об авторском праве выдано 21 октября 2025 г. AGEPI на программное обеспечение XCLABEL. Весь исходный код и ИС принадлежат Марифу Бергану.',
    'xc.ip.h2':       'Защита интеллектуальной собственности',
    'xc.cta.h2':      'Готовы создать новую эру пространственных коммуникаций?',
    'xc.cta.p':       'XCLABEL — запатентованная платформа для иммерсивной идентичности. Давайте создадим пилоты для Google, Meta и ведущих площадок.',
    'xc.nav.problem': 'Проблема',
    'xc.nav.demo':    'Демо',
    'xc.nav.tech':    'Технология',
    'xc.nav.market':  'Рынок',
    'xc.nav.revenue': 'Доход',
    'xc.nav.partners':'Партнёры',
    'xc.nav.pitch':   'Запросить питч',

    'ap.h1':          'XCLABEL Airport — AR-решение для аэропортов',
    'ap.h1.p':        'Трансформируйте опыт пассажиров с AR-навигацией в реальном времени и бесконтактной верификацией. От регистрации до посадки.',
    'ap.btn1':        'Запросить демо',
    'ap.btn2':        'Изучить технологию',
    'ap.m1':          'Патент принадлежит Марифу Бергану',
    'ap.m2':          'AR-навигация + Распознавание лиц + BLE',
    'ap.m3':          'Контрольные точки на 40% быстрее',
    'ap.nav.challenge':'Проблема',
    'ap.nav.nav':     'Навигация',
    'ap.nav.security':'Безопасность',
    'ap.nav.tech':    'Технология',
    'ap.nav.benefits':'Преимущества',
    'ap.nav.market':  'Рынок',
    'ap.nav.demo':    'Запросить демо',

    'oht.h1':         'Owl Hoot Tech',
    'oht.h1.sub':     'Создаём корпоративное ПО будущего — сегодня.',
    'oht.h1.p':       'Европейская deep-tech студия, основанная в 2026 году, с 10 специализированными продуктами в области AR, логистики, ERP, BI, RPA и доступности. Целевой рынок — более EUR 400B+ в совокупности.',
    'oht.h1.btn1':    'Информация для инвесторов',
    'oht.h1.btn2':    'Стать партнёром',
    'oht.mission.h2': 'Наша миссия',
    'oht.mission.p':  'Создавать целенаправленно спроектированные программные решения — каждый продукт решает конкретную высокоценную проблему для корпоративных клиентов с качеством, безопасностью и масштабируемостью.',
    'oht.vision.h2':  'Наше видение',
    'oht.vision.p':   'Стать ведущей европейской deep-tech студией, создающей гипер-специализированное корпоративное ПО, которое трансформирует бизнес по всему миру.',
    'oht.products.h2':'Наши 10 продуктов',
    'oht.products.sub':'Каждый продукт — лучший инструмент для своей задачи: глубокая специализация, облачная архитектура, корпоративные стандарты.',
    'oht.inv.h2':     'Для инвесторов',
    'oht.inv.sub':    'Редкая возможность: 10 корпоративных продуктов, совокупный TAM EUR 400B+, привлекаем EUR 2–15M.',
    'oht.inv.ask.h3': 'Инвестиционный запрос',
    'oht.inv.round':  'Тип раунда',
    'oht.inv.round.v':'Seed / Pre-Series A',
    'oht.inv.amount': 'Сумма привлечения',
    'oht.inv.amount.v':'EUR 2M (минимум) — EUR 15M (полный раунд)',
    'oht.inv.val':    'Оценка компании',
    'oht.inv.val.v':  'EUR 8–15M до инвестиций',
    'oht.inv.use':    'Использование средств',
    'oht.inv.use.v':  'Разработка (45%), Продажи и маркетинг (25%), Операции (15%), Инфраструктура (10%), Резерв (5%)',
    'oht.inv.run':    'Runway',
    'oht.inv.run.v':  '18–24 месяца до Series A / выхода на безубыточность',
    'oht.inv.metrics.h3':'Ключевые метрики',
    'oht.inv.m1':     'Продуктов в портфеле',
    'oht.inv.m1.v':   '10 корпоративных программных продуктов',
    'oht.inv.m2':     'Совокупный TAM',
    'oht.inv.m2.v':   'USD 304B+ в глобальном масштабе',
    'oht.inv.m3':     'Прогноз ARR на 3-й год',
    'oht.inv.m3.v':   'EUR 8.4M (портфель)',
    'oht.inv.m4':     'Целевая валовая маржа',
    'oht.inv.m4.v':   '70–80% на масштабе (SaaS-продукты)',
    'oht.inv.m5':     'Бизнес-модель',
    'oht.inv.m5.v':   'SaaS + корпоративная лицензия + профессиональные услуги',
    'oht.inv.m6':     'Целевые рынки',
    'oht.inv.m6.v':   'Европа, MENA, Северная Америка',
    'oht.inv.cta':    'Запросить инвестиционный питч',
    'oht.partner.h2': 'Стать партнёром',
    'oht.partner.sub':'Мы активно ищем реселлеров, системных интеграторов и технологических партнёров для расширения присутствия в Европе и MENA.',
    'oht.partner.1.h3':'Реселлер-партнёры',
    'oht.partner.1.p':'Продавайте и внедряйте продукты OHT под своим брендом. Конкурентная маржа, полная техподдержка, совместный маркетинг.',
    'oht.partner.2.h3':'Технологическая интеграция',
    'oht.partner.2.p':'Подключите вашу платформу к продуктам OHT через открытые API. Расширьте предложение специализированными инструментами.',
    'oht.partner.3.h3':'Стратегические инвестиции',
    'oht.partner.3.p':'Соинвестируйте и получите долю в капитале. Доступ к полным финансовым данным, права наблюдателя в совете директоров.',
    'oht.partner.btn': 'Связаться для партнёрства',
    'oht.cta.h2':     'Готовы создать что-то выдающееся?',
    'oht.cta.p':      'Будь вы инвестор, партнёр или корпоративный клиент — мы рады пообщаться.',
    'oht.footer':     '© {year} Owl Hoot Tech. Основана в 2026. Все права защищены.',
  },

  ro: {
    'nav.home':       'Acasă',
    'nav.solutions':  'Soluții',
    'nav.contact':    'Contact',
    'nav.oht':        'Owl Hoot Tech',

    'idx.tagline':    'Soluții AR Revoluționare',
    'idx.desc':       'Tehnologie brevetată care transformă rețelele digitale și experiențele spațiale. Alegeți soluția potrivită mai jos.',
    'idx.choose':     'Alegeți Soluția',

    'xc.subtitle':    'Networking Digital & Panouri AR',
    'xc.desc':        'Recunoaștere facială instantanee + BLE = cărți de vizită digitale automate + panouri AR inteligente care nu pot fi blocate. Pentru întreprinderi, creatori, evenimente și retail.',
    'xc.btn':         'Explorați XCLABEL',
    'xc.stat1.label': 'Oportunitate de Piață',
    'xc.stat2.label': 'Timp de Conectare',
    'xc.stat3.label': 'Rază BLE',

    'ap.subtitle':    'Soluție AR Completă pentru Aeroporturi',
    'ap.desc':        'Navigare AR în timp real + verificare de securitate fără contact pentru aeroporturi. Reduceți timpii de control cu 40%, îmbunătățind siguranța și confortul pasagerilor.',
    'ap.btn':         'Explorați XCLABEL Airport',
    'ap.stat1.label': 'Securitate Mai Rapidă',
    'ap.stat2.label': 'Verificare',
    'ap.stat3.label': 'Navigare AR',

    'oht.subtitle':   'Studio Software Enterprise — 10 Produse',
    'oht.desc':       'Compania din spatele XCLABEL. Owl Hoot Tech construiește software enterprise specializat în ERP, BI, RPA, logistică, accesibilitate și AR — vizând EUR 400B+ în piețe adresabile combinate.',
    'oht.btn':        'Află despre OHT',
    'oht.stat1.val':  '10+',
    'oht.stat1.label':'Produse',
    'oht.stat2.val':  'EUR 2–15M',
    'oht.stat2.label':'Căutăm',
    'oht.stat3.val':  'EUR 8.4M',
    'oht.stat3.label':'ARR Anul 3',

    'ben.title':      'Platformă Tehnologică Unificată',
    'ben.sub':        'Ambele soluții sunt alimentate de aceeași infrastructură AR brevetată',
    'ben.1.title':    'Brevet Protejat',
    'ben.1.desc':     'Tehnologia de bază aparține lui Marif Bergan cu protecție internațională',
    'ben.2.title':    'Scară Globală',
    'ben.2.desc':     'Compatible cu ARCore și Spark AR, gata pentru implementare mondială',
    'ben.3.title':    'Sincronizare în Timp Real',
    'ben.3.desc':     'Fuziune BLE + AR cu arhitectură offline-first',
    'ben.4.title':    'Ocean Albastru',
    'ben.4.desc':     'Fără concurenți direcți în spațiul AR + BLE networking',

    'cta.idx.h2':     'Gata să transformați industria dvs.?',
    'cta.idx.p':      'Indiferent dacă căutați networking digital sau navigație aeroportuară, XCLABEL are soluția brevetată.',
    'cta.note':       'sau sunați la +373 68 761 110',

    'footer.copy':    '© {year} XCLABEL. Brevet deținut de Marif Bergan. Recunoaștere facială + BLE + Smart AR.',
    'footer.contact': 'Contact',

    // ── OHT Product cards ─────────────────────────────────────────
    'oht.prod.xc.tag':      'AR · Networking',
    'oht.prod.xc.desc':     'Recunoaștere facială brevetată + BLE = cărți de vizită digitale automate în 0,3 s. Panouri AR inteligente ancorate pe suprafețe reale care nu pot fi blocate de ad-blockere. Pentru întreprinderi, evenimente live, retail și aplicații de dating.',
    'oht.prod.ap.tag':      'AR · Aviație',
    'oht.prod.ap.desc':     'Navigare AR în timp real și verificare fără contact a pasagerilor pentru aeroporturi. Balise BLE, puncte de control cu recunoaștere facială (0,3 s/pasager), integrare bilete și navigare multi-etaj. Îmbarcare cu 40% mai rapidă.',
    'oht.prod.perch.tag':   'ERP · IMM',
    'oht.prod.perch.desc':  'ERP on-premise ușor pentru IMM-uri — mai simplu decât 1C, mai ieftin decât SAP. Module: Finanțe (partidă dublă, TVA), Stocuri (FIFO), CRM, Vânzări, Achiziții, HR cu salarizare Moldova (CAS/CASS). Import XML 1C, FastAPI REST, Studio Docker-ready.',
    'oht.prod.strix.tag':   'BI · Analiză',
    'oht.prod.strix.desc':  'Platformă BI self-service care se conectează la baze de date SQL, Excel, Perch ERP și Glide RPA. Constructor de dashboarduri drag-and-drop, rapoarte PDF programate, reguli de alertă bazate pe metrici. On-premise, fără dependență cloud.',
    'oht.prod.glide.tag':   'RPA · Automatizare',
    'oht.prod.glide.desc':  'Platformă RPA Python-nativă — mai rapidă decât UiPath, zero taxe de licențiere. Definiți fluxuri în YAML, automatizați browsere cu Playwright, orchestrați REST API, rulați joburi concurent via asyncio. MIT open core, Docker-ready.',
    'oht.prod.hollow.tag':  'WMS · Logistică',
    'oht.prod.hollow.desc': 'Sistem virtual de management al depozitelor. Grilă 3D configurabilă (rânduri × coloane × niveluri), management zone cu coduri de culori, intrări stoc per poziție și backend FastAPI REST cu dashboard Studio în timp real.',
    'oht.prod.telepat.tag': 'Accesibilitate · Privire',
    'oht.prod.telepat.desc':'Control telefon hands-free prin urmărirea privirii în timp real. Camera frontală și modelul TensorFlow Lite urmăresc continuu poziția privirii — rămâneți pe un element pentru a-l tasta. Click prin zâmbet, calibrare, preset PRECISION.',
    'oht.prod.xproj.tag':   'AR · Afișaj Wireless',
    'oht.prod.xproj.desc':  'Proiector AR de suprafețe + oglindă ecran wireless într-o singură aplicație. Modul AR folosește ARCore/Sceneform. Modul wireless transmite ecranul la până la 60 fps H.264 (12 Mbps) prin Google Nearby Connections — fără cabluri sau router.',
    'oht.prod.xcdock.tag':  'Bluetooth · Hub',
    'oht.prod.xcdock.desc': 'Transformă orice telefon Android într-un hub Bluetooth virtual. Scanează și gestionează simultan căști, boxe, televizoare, computere prin BT Classic, BLE și Wi-Fi Direct. Bare RSSI în timp real, detectare tip dispozitiv, motor VirtualHub.',
    'oht.prod.icswigl.tag': 'Accesibilitate · Afișaj',
    'oht.prod.icswigl.desc':'Scalare font și afișaj la nivel de sistem Android, controlată prin voce. Spuneți "Hey Wigl set 3" pentru a schimba instant dimensiunea textului, sau "Wigl Wigl" pentru lanternă de urgență. Mod TV, cititor web autonom cu zoom personalizat.',

    'xch1':           'XCLABEL — Networking Digital AR Revoluționar',
    'xch1.p':         'Tehnologie premieră mondială: recunoaștere facială automată + BLE = cărți de vizită digitale instantanee + panouri AR inteligente care nu pot fi blocate.',
    'xch1.btn1':      'Programați un Demo',
    'xch1.btn2':      'Explorați Platforma',
    'xch1.m1':        'Brevet deținut de Marif Bergan',
    'xch1.m2':        'Recunoaștere Facială + BLE + AR Smart Billboards',
    'xch1.m3':        'Ocean Albastru · Fără concurenți direcți',
    'xc.card.h3':     'Panou AR Inteligent Imersiv',
    'xc.card.p':      'Suprapunere AR transparentă cu identitate verificată, analiză în timp real și conținut dinamic.',
    'xc.demo.eyebrow':'Previzualizare live',
    'xc.demo.h2':     'Suprapuneri față-în-față instantanee care finalizează ciclul în secunde.',
    'xc.demo.p':      'XCLABEL identifică fața, extrage acoperirea verificată și livrează butoane acționabile care funcționează chiar și offline.',
    'xc.demo.li1':    '<strong>Identitate în prim-plan:</strong> status relație și metrici de audiență certificate dintr-o privire.',
    'xc.demo.li2':    '<strong>Engagement monetizabil:</strong> „Deschide" duce la orice destinație, „Copiază" trimite linkul pe orice canal.',
    'xc.demo.li3':    '<strong>Punte offline-online:</strong> sincronizare BLE brevetată înlocuiește codurile QR și NFC.',
    'xc.demo.btn1':   'Rezervați un tur live',
    'xc.demo.btn2':   'Vezi stack-ul tehnologic',
    'xc.prob.h2':     'Problema: networking ineficient costă bani',
    'xc.prob.h3a':    'Realitatea actuală',
    'xc.prob.li1a':   'Peste 15 secunde pentru a schimba informații de contact',
    'xc.prob.li2a':   '40% din cărțile fizice se pierd sau deteriorează',
    'xc.prob.li3a':   'Zero actualizări sau sincronizare în timp real',
    'xc.prob.li4a':   'Imposibil de blocat concurenții din publicitate offline',
    'xc.prob.li5a':   'Creatorii și evenimentele pierd lead-uri calde',
    'xc.prob.h3b':    'Impact pe piață',
    'xc.prob.li1b':   'Oportunitate de piață $50B+ · creștere 25% CAGR',
    'xc.prob.li2b':   'Peste 250M utilizatori afectați de pierderea datelor',
    'xc.prob.li3b':   'Pierderea datelor first-party = cheltuieli irosite',
    'xc.prob.li4b':   'Creatorii Google/Meta nu au conversii offline verificate',
    'xc.tech.h2':     'Două tehnologii revoluționare într-una',
    'xc.tech.p':      'Fluxul de lucru brevetat XCLABEL care combină viziunea computerizată, BLE și media AR spațial.',
    'xc.tech.s1.h3':  'ID-uri Digitale Instantanee',
    'xc.tech.s1.p':   'Recunoaștere facială automată în 0,3 secunde + handshake BLE fără scanare.',
    'xc.tech.s2.h3':  'Sincronizare Date în Timp Real',
    'xc.tech.s2.p':   'Raza de 10 metri actualizează Google Contacts și Meta Business Suite în timp real.',
    'xc.tech.s3.h3':  'Panouri AR Inteligente',
    'xc.tech.s3.p':   'Suprapuneri video transparente cu analiză, compatibile ARCore/Spark AR.',
    'xc.uses.h3':     'Cazuri de utilizare multi-industrie',
    'xc.uses.li1':    '<strong>Întreprinderi</strong> — sedii centrale, târguri comerciale, summit-uri executive',
    'xc.uses.li2':    '<strong>Creatori și influenceri</strong> — întâlniri, tururi, activări fan',
    'xc.uses.li3':    '<strong>Retail și campusuri</strong> — merchandising geo-fenced',
    'xc.uses.li4':    '<strong>Dating și social</strong> — schimb de identitate cu dovadă offline',
    'xc.market.h2':   'Oportunitate de piață $50B+',
    'xc.market.a1h3': 'Piața totală adresabilă',
    'xc.market.a1p':  'Identitate digitală ($2.3T), publicitate AR/VR ($455B), soluții networking ($15B).',
    'xc.market.a2h3': 'Piața adresabilă deservită',
    'xc.market.a2p':  '$8B SAM: B2C și B2B (500K corporații + 50K agenții).',
    'xc.market.a3h3': 'Viteza de creștere',
    'xc.market.a3p':  '25% CAGR fără concurenți direcți — o adevărată oportunitate ocean albastru.',
    'xc.market.a4h3': 'Avantajul vizibilității',
    'xc.market.a4p':  'Panourile inteligente sunt 100% vizibile, ocolesc ad-blockerele.',
    'xc.moat.h2':     'Avantajul primului jucător: tehnologie brevetată',
    'xc.rev.h2':      'Surse multiple de venituri (marje mari)',
    'xc.rev.a1h3':    'Abonamente creatori',
    'xc.rev.a1p':     '$4.99/lună · 5M creatori · $600M venituri anuale · marjă 80-90%.',
    'xc.rev.a2h3':    'Inventar publicitar AR',
    'xc.rev.a2p':     '$2.50 per afișare · 100M afișări până la Anul 3 · $250M venituri.',
    'xc.rev.a3h3':    'Licențiere enterprise',
    'xc.rev.a3p':     '$99–$999/lună · 10K clienți corporate · $240M venituri.',
    'xc.rev.a4h3':    'Licențiere API și platformă',
    'xc.rev.a4p':     '$0.10 per apel API · 1B apeluri până la Anul 3 · $100M venituri.',
    'xc.fin.h2':      'Traiectoria financiară',
    'xc.fin.y1h3':    '$2.5M venituri',
    'xc.fin.y1p':     'Piloți enterprise inițiali + abonamente creatori.',
    'xc.fin.y2h3':    '$31.5M venituri',
    'xc.fin.y2p':     'Creștere 12.6× cu lansarea publicității și parteneriatele Advantage+.',
    'xc.fin.y3h3':    '$195M venituri',
    'xc.fin.y3p':     'Creștere 6.2× — creatori, dating și retail la scară.',
    'xc.fin.y5h3':    '$1.44B venituri',
    'xc.fin.y5p':     'Implementare globală cu marje 80–90%, CAC $15, LTV $180.',
    'xc.val.h3':      'Investiție și Achiziție',
    'xc.val.li1':     'Căutăm: EUR 2–15M — achiziție strategică sau investiție în stadiu incipient',
    'xc.val.li2':     'ROI pentru achizitor: 156% IRR pe traiectoria pe termen lung a platformei',
    'xc.val.li3':     'Adoptare consumatori: 60% utilizare până la Anul 3',
    'xc.val.li4':     'Marjă brută: 80–90% cu venituri recurente',
    'xc.part.h2':     'Compatibilitate strategică cu Google și Meta',
    'xc.part.a3h3':   'Opțiuni de tranzacție',
    'xc.part.a3p':    'Achiziție strategică (EUR 2–15M), rundă de investiție seed (EUR 2–8M) sau licențiere exclusivă IP cu plată în avans. Demo funcțional disponibil la cerere.',
    'xc.ip.pat.step': 'Brevet',
    'xc.ip.pat.h3':   'AGEPI Nr. 7598 — Etapă finală de examinare',
    'xc.ip.pat.p':    'Depus la 18 noiembrie 2025. Statut curent: examinare de fond (cerere de examinare de fond) — etapa finală înainte de acordare. Flux de bază: recunoaștere facială + schimb BLE instant + panouri AR inteligente.',
    'xc.ip.copy.step':'Drept de autor',
    'xc.ip.copy.h3':  'Seria PC Nr. 8320 — Software înregistrat',
    'xc.ip.copy.p':   'Adeverință privind înscrierea dreptului de autor eliberată la 21 octombrie 2025 de AGEPI pentru software-ul XCLABEL. Codul sursă complet și PI aparțin lui Marif Bergan.',
    'xc.ip.h2':       'Protecția proprietății intelectuale',
    'xc.cta.h2':      'Gata să co-creați noua eră a networking-ului spațial?',
    'xc.cta.p':       'XCLABEL este platforma brevetată pentru identitate imersivă. Să construim piloți pentru Google, Meta și locații de top.',
    'xc.nav.problem': 'Problemă',
    'xc.nav.demo':    'Demo',
    'xc.nav.tech':    'Tehnologie',
    'xc.nav.market':  'Piață',
    'xc.nav.revenue': 'Venituri',
    'xc.nav.partners':'Parteneri',
    'xc.nav.pitch':   'Solicitați Pitch',

    'ap.h1':          'XCLABEL Airport — Soluție AR Completă pentru Aeroporturi',
    'ap.h1.p':        'Transformați experiența pasagerilor cu navigare AR în timp real și verificare de securitate fără contact. De la check-in la îmbarcare.',
    'ap.btn1':        'Programați Demo',
    'ap.btn2':        'Vezi Tehnologia',
    'ap.m1':          'Brevet deținut de Marif Bergan',
    'ap.m2':          'Navigare AR + Recunoaștere Facială + BLE',
    'ap.m3':          'Puncte de control cu 40% mai rapide',
    'ap.nav.challenge':'Provocare',
    'ap.nav.nav':     'Navigare',
    'ap.nav.security':'Securitate',
    'ap.nav.tech':    'Tehnologie',
    'ap.nav.benefits':'Beneficii',
    'ap.nav.market':  'Piață',
    'ap.nav.demo':    'Solicitați Demo',

    'oht.h1':         'Owl Hoot Tech',
    'oht.h1.sub':     'Construim Software Enterprise al Viitorului — Astăzi.',
    'oht.h1.p':       'Studio deep-tech european fondat în 2026, cu 10 produse software enterprise specializate în AR, logistică, ERP, BI, RPA și accesibilitate. Piață adresabilă combinată de peste EUR 400B+.',
    'oht.h1.btn1':    'Informații pentru Investitori',
    'oht.h1.btn2':    'Deveniți Partener',
    'oht.mission.h2': 'Misiunea Noastră',
    'oht.mission.p':  'Să livrăm soluții software proiectate cu scop — fiecare produs rezolvă o problemă de înaltă valoare pentru clienți enterprise, cu calitate, securitate și scalabilitate.',
    'oht.vision.h2':  'Viziunea Noastră',
    'oht.vision.p':   'Să devenim liderul european în software enterprise hiper-specializat care transformă modul în care afacerile operează și concurează global.',
    'oht.products.h2':'Cele 10 Produse ale Noastre',
    'oht.products.sub':'Fiecare produs este cel mai bun instrument pentru sarcina sa — specializare profundă, cloud-native, standarde enterprise.',
    'oht.inv.h2':     'Pentru Investitori',
    'oht.inv.sub':    'O oportunitate rară: 10 produse enterprise, TAM combinat EUR 400B+, căutăm EUR 2–15M finanțare seed.',
    'oht.inv.ask.h3': 'Cererea de Investiție',
    'oht.inv.round':  'Tip de Rundă',
    'oht.inv.round.v':'Seed / Pre-Series A',
    'oht.inv.amount': 'Sumă Căutată',
    'oht.inv.amount.v':'EUR 2M (minim) — EUR 15M (rundă completă)',
    'oht.inv.val':    'Evaluare (indicativă)',
    'oht.inv.val.v':  'EUR 8–15M pre-money',
    'oht.inv.use':    'Utilizarea Fondurilor',
    'oht.inv.use.v':  'Inginerie (45%), Vânzări & Marketing (25%), Operațiuni (15%), Infrastructură (10%), Rezervă (5%)',
    'oht.inv.run':    'Runway',
    'oht.inv.run.v':  '18–24 luni până la Series A / breakeven pe produsele principale',
    'oht.inv.metrics.h3':'Metrici Cheie',
    'oht.inv.m1':     'Produse în portofoliu',
    'oht.inv.m1.v':   '10 produse software enterprise',
    'oht.inv.m2':     'TAM combinat',
    'oht.inv.m2.v':   'USD 304B+ la nivel global',
    'oht.inv.m3':     'Proiecție ARR Anul 3',
    'oht.inv.m3.v':   'EUR 8.4M (portofoliu combinat)',
    'oht.inv.m4':     'Marjă brută țintă',
    'oht.inv.m4.v':   '70–80% la scară (produse SaaS)',
    'oht.inv.m5':     'Model de business',
    'oht.inv.m5.v':   'SaaS + licență enterprise + servicii profesionale',
    'oht.inv.m6':     'Piețe țintă',
    'oht.inv.m6.v':   'Europa, MENA, America de Nord',
    'oht.inv.cta':    'Solicitați Pitch Deck pentru Investitori',
    'oht.partner.h2': 'Deveniți Partener',
    'oht.partner.sub':'Căutăm activ reselleri, integratori de sisteme și parteneri tehnologici pentru a extinde prezența în Europa și MENA.',
    'oht.partner.1.h3':'Parteneri Reselleri',
    'oht.partner.1.p':'Vindeți și implementați produse OHT sub brandul dvs. Marje competitive, suport tehnic complet, resurse de co-marketing.',
    'oht.partner.2.h3':'Integrare Tehnologică',
    'oht.partner.2.p':'Conectați platforma dvs. la produsele OHT prin API-uri deschise. Extindeți oferta cu instrumente specializate de top.',
    'oht.partner.3.h3':'Investiție Strategică',
    'oht.partner.3.p':'Co-investiți și obțineți o poziție de capital. Acces la date financiare complete, drepturi de observator în consiliu.',
    'oht.partner.btn': 'Contactați-ne pentru Parteneriat',
    'oht.cta.h2':     'Gata să construiți ceva extraordinar?',
    'oht.cta.p':      'Indiferent că sunteți investitor, partener sau client enterprise — ne-ar face plăcere să discutăm.',
    'oht.footer':     '© {year} Owl Hoot Tech. Fondată în 2026. Toate drepturile rezervate.',
  }
};

// ── Core translation engine ───────────────────────────────────────────────────
function setLang(lang) {
  if (!TRANSLATIONS[lang]) return;
  const t = TRANSLATIONS[lang];

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (t[key] !== undefined) el.setAttribute('placeholder', t[key]);
  });

  document.querySelectorAll('[data-i18n]').forEach(el => {
    if (el.innerHTML.includes('{year}')) {
      el.innerHTML = el.innerHTML.replace('{year}', new Date().getFullYear());
    }
  });

  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });

  document.documentElement.lang = lang;
  try { localStorage.setItem('xclabel_lang', lang); } catch(e) {}
}

// ── Init on DOM ready ─────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  let lang = 'en';
  try { lang = localStorage.getItem('xclabel_lang') || 'en'; } catch(e) {}
  if (!TRANSLATIONS[lang]) lang = 'en';
  setLang(lang);
});
